SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME,
SUM(FOOD_ORDER.AMOUNT * FOOD_PRODUCT.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER
INNER JOIN FOOD_PRODUCT ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE MONTH(FOOD_ORDER.PRODUCE_DATE) = 5 AND YEAR(FOOD_ORDER.PRODUCE_DATE) = 2022
GROUP BY FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
